In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_digits
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score


In [3]:
digit_data= load_digits()

In [4]:
X_train, X_test, y_train, y_test = train_test_split(digit_data['data'], digit_data['target'])


In [5]:
svm = SVC(kernel='rbf', C=1).fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [6]:
rndm_frst= RandomForestClassifier(n_estimators=100).fit(X_train, y_train)
rndm_frst.score(X_test, y_test)

0.9844444444444445

In [7]:
log_reg= LogisticRegression().fit(X_train, y_train)
log_reg.score(X_test, y_test)

d:\Artificial Intelligence\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9577777777777777

In [8]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
	print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
def get_score(model, X_train, X_test, y_train, y_test):
	model.fit(X_train, y_train)
	return model.score(X_test, y_test)

In [17]:
folds = StratifiedKFold(n_splits=5)
scores_log_reg = []
scores_svm = []
scores_rndm_frst = []

for train_index, test_index in folds.split(digit_data.data, digit_data.target):
	X_train, X_test, y_train, y_test = digit_data.data[train_index], digit_data.data[test_index],\
										digit_data.target[train_index], digit_data.target[test_index]
	scores_log_reg.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
	scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
	scores_rndm_frst.append(get_score(RandomForestClassifier(n_estimators=30), X_train, X_test, y_train, y_test))

print(scores_log_reg)
print(scores_svm)
print(scores_rndm_frst)


d:\Artificial Intelligence\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Artificial Intelligence\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

[0.9222222222222223, 0.8694444444444445, 0.9415041782729805, 0.9387186629526463, 0.8969359331476323]
[0.9611111111111111, 0.9444444444444444, 0.9832869080779945, 0.9888579387186629, 0.9387186629526463]
[0.925, 0.9055555555555556, 0.9415041782729805, 0.958217270194986, 0.9025069637883009]


d:\Artificial Intelligence\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## Same funtion we can do using cross_val_score method

In [23]:
cross_val_score(LogisticRegression(max_iter=100), digit_data.data, digit_data.target, cv=4)

d:\Artificial Intelligence\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Artificial Intelligence\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

array([0.93555556, 0.90423163, 0.94877506, 0.91759465])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=30), digit_data.data, digit_data.target, cv=4)

array([0.93111111, 0.90200445, 0.9532294 , 0.93318486])

In [25]:
cross_val_score(SVC(), digit_data.data, digit_data.target, cv=4)

array([0.96222222, 0.96659243, 0.98218263, 0.95100223])